module.exports = {
  getTorrentInfo: data => ({
    'd.is_open': data[0],
    'd.is_hash_checking': data[1],
    'd.is_hash_checked': data[2],
    'd.get_state': data[3],
    'd.get_name': data[4],
    'd.get_size_bytes': data[5],
    'd.get_completed_chunks': data[6],
    'd.get_size_chunks': data[7],
    'd.get_bytes_done': data[8],
    'd.get_up_total': data[9],
    'd.get_ratio': data[10],
    'd.get_up_rate': data[11],
    'd.get_down_rate': data[12],
    'd.get_chunk_size': data[13],
    'd.get_custom1': data[14],
    'd.get_peers_accounted': data[15],
    'd.get_peers_not_connected': data[16],
    'd.get_peers_connected': data[17],
    'd.get_peers_complete': data[18],
    'd.get_left_bytes': data[19],
    'd.get_priority': data[20],
    'd.get_state_changed': data[21],
    'd.get_skip_total': data[22],
    'd.get_hashing': data[23],
    'd.get_chunks_hashed': data[24],
    'd.get_base_path': data[25],
    'd.get_creation_date': data[26],
    'd.get_tracker_focus': data[27],
    'd.is_active': data[28],
    'd.get_message': data[29],
    'd.get_custom2': data[30],
    'd.get_free_diskspace': data[31],
    'd.is_private': data[32],
    'd.is_multi_file': data[33],
  }),
};
